### ISSUE TITLE
Demonman Charge Meter Does Not Merge Properly

### ISSUE THREAD

**Issue by aFloatingEcho** [cooolbros/hud-merger#8]
When attempting to merge EVE hud (https://steamcommunity.com/groups/eve-hud) and flawhud (https://github.com/CriticalFlaw/flawhud) together, it fails to merge the Demoman Charge Property. I presume it's under item charge, but I haven't found it listed specifically between the merges.

Screenshot below is what was merged between the huds.
![image](https://github.com/cooolbros/hud-merger/assets/60680403/ca3c3c38-512d-4e05-8880-1b6fb0b59556)

Screenshot of the merged huds:
![image](https://github.com/cooolbros/hud-merger/assets/60680403/ae134682-a215-48db-a1cd-7cbb74f6dfcf)

Screenshot of flawhud:
![image](https://github.com/cooolbros/hud-merger/assets/60680403/88b292ec-b841-4812-9336-2355908e70bb)

Screenshot of EVE hud:
![image](https://github.com/cooolbros/hud-merger/assets/60680403/4845e7a5-cad7-4af0-9713-2f66d7aad182)

**Comment by cooolbros** [comment]
Hi sorry for the late response. The demo stickies label and charge meter previously werent even available in the HUD merger, I think because the elements are usually put together, but the panel grouping I decided on was "Item Charge Counters" and "Item Charge Meters", meaning the demoman panels would have to be split or go into both.

I added a new panel "Demoman Pipes Label And Charge Meter" in 62073cf

**Comment by cooolbros** [comment]
Added in 2.0.3
